### ISSUE TITLE
[BUG] Bed obstruction rules/spawning on top of bed

### ISSUE THREAD

**Issue by xoltiv** [Sauilitired/Hyperverse#33]
**Describe the bug**
Players spawn on top of their bed instead of next to it.  Also, when the bed is obstructed, the player is taken to a higher y level.

**To Reproduce**
1. Build a hut with a 2-high ceiling and 3x4 interior
2. Place a bed in the center and sleep
3. Respawn (You should spawn on the roof, directly above the bed)

**Expected behavior**
In vanilla, the player is spawned adjacent to the bed according to [these](https://minecraft.gamepedia.com/Bed#Setting_the_spawn_point) rules.  Also, if the bed is obstructed, the player is taken to spawn instead of being spawned at a higher y level.

**Comment by Sauilitired** [comment]
Commit https://github.com/Sauilitired/Hyperverse/commit/f3f1c6577f7f65052abc11a0b46b9172825a228b will fix the locations, so that you're no longer on top of the bed. I'll need to re-visit obstruction. It already checks if the bed has been removed and sends you to spawn if that's the case, it should also check if there are blocks directly above the bed.
